# To change this license header, choose License Headers in Project Properties.
# To change this template file, choose Tools | Templates
# and open the template in the editor.
# To change this template, choose Tools | Templates
# and open the template in the editor.

companyId=1001

acctYear=20212022
startDate=2021-04-01
endDate=2022-03-31
email.host=smtp.gmail.com
email.from=bhaumikramani@gmail.com
email.to=bhaumikramani@gmail.com
newword=1a53a5c
basicpath=E:\\SQLBackup\\2021\\
