##
# BILLING PROPERTIES
RevenueHeads=7,9
TaxHeads=25
ExpenseHeads=6,8
DiscountHeads=6,7,8,9
OtherChargesHeads=
BANKACCTPARENTS=18,28,30
ProfitNLossCCID=1016
DiffInOpnBalCCID=1017
CreditorsParent=29
DebtorsParent=22
ReportPath=E:\\Bhaumik\\SHIKHAR\\web\\reports\\
CUT_OFF_DATE=2018-04-01